from .tools import Executor

map = {
    "twitter_tweets_id_get": Executor.twitter_tweets_id_get,
    "twitter_tweets_id_delete": Executor.twitter_tweets_id_delete,
    "twitter_tweets_get": Executor.twitter_tweets_get,
    "twitter_tweets_post": Executor.twitter_tweets_post,
    "twitter_users_id_get": Executor.twitter_users_id_get,
    "twitter_users_get": Executor.twitter_users_get,
    "twitter_users_by_username_username_get": Executor.twitter_users_by_username_username_get,
    "twitter_users_by_get": Executor.twitter_users_by_get,
    "twitter_find_my_user": Executor.twitter_find_my_user,
    "twitter_users_id_followers_get": Executor.twitter_users_id_followers_get,
    "twitter_users_id_following_get": Executor.twitter_users_id_following_get,
    "twitter_users_id_following_post": Executor.twitter_users_id_following_post,
    "twitter_users_source_user_id_following_target_user_id_delete": Executor.twitter_users_source_user_id_following_target_user_id_delete,
    "twitter_users_id_blocking_post": Executor.twitter_users_id_blocking_post,
    "twitter_users_id_blocking_get": Executor.twitter_users_id_blocking_get,
    "twitter_users_source_user_id_blocking_target_user_id_delete": Executor.twitter_users_source_user_id_blocking_target_user_id_delete,
    "twitter_lists_id_get": Executor.twitter_lists_id_get,
    "twitter_lists_id_delete": Executor.twitter_lists_id_delete,
    "twitter_lists_id_put": Executor.twitter_lists_id_put,
    "twitter_users_id_owned_lists_get": Executor.twitter_users_id_owned_lists_get,
    "twitter_lists_post": Executor.twitter_lists_post,
    "twitter_lists_id_tweets_get": Executor.twitter_lists_id_tweets_get,
    "twitter_lists_id_members_post": Executor.twitter_lists_id_members_post,
    "twitter_lists_id_members_get": Executor.twitter_lists_id_members_get,
    "twitter_lists_id_members_user_id_delete": Executor.twitter_lists_id_members_user_id_delete,
    "twitter_users_id_list_memberships_get": Executor.twitter_users_id_list_memberships_get,
    "twitter_users_id_followed_lists_post": Executor.twitter_users_id_followed_lists_post,
    "twitter_users_id_followed_lists_get": Executor.twitter_users_id_followed_lists_get,
    "twitter_users_id_followed_lists_list_id_delete": Executor.twitter_users_id_followed_lists_list_id_delete,
    "twitter_lists_id_followers_get": Executor.twitter_lists_id_followers_get,
    "twitter_users_id_pinned_lists_post": Executor.twitter_users_id_pinned_lists_post,
    "twitter_users_id_pinned_lists_get": Executor.twitter_users_id_pinned_lists_get,
    "twitter_list_user_unpin": Executor.twitter_list_user_unpin,
    "twitter_users_id_muting_post": Executor.twitter_users_id_muting_post,
    "twitter_users_id_muting_get": Executor.twitter_users_id_muting_get,
    "twitter_users_source_user_id_muting_target_user_id_delete": Executor.twitter_users_source_user_id_muting_target_user_id_delete,
    "twitter_tweets_id_quote_tweets_get": Executor.twitter_tweets_id_quote_tweets_get,
    "twitter_hide_reply_by_id": Executor.twitter_hide_reply_by_id,
    "twitter_tweets_search_recent_get": Executor.twitter_tweets_search_recent_get,
    "twitter_tweets_search_all_get": Executor.twitter_tweets_search_all_get,
    "twitter_tweets_counts_recent_get": Executor.twitter_tweets_counts_recent_get,
    "twitter_tweets_counts_all_get": Executor.twitter_tweets_counts_all_get,
    # "twitter_tweets_search_stream_rules_post": Executor.twitter_tweets_search_stream_rules_post,
    # "twitter_tweets_search_stream_rules_get": Executor.twitter_tweets_search_stream_rules_get,
    # "twitter_tweets_search_stream_get": Executor.twitter_tweets_search_stream_get,
    # "twitter_tweets_sample_stream_get": Executor.twitter_tweets_sample_stream_get,
    # "twitter_get_tweets_sample10_stream": Executor.twitter_get_tweets_sample10_stream,
    "twitter_spaces_id_get": Executor.twitter_spaces_id_get,
    "twitter_spaces_get": Executor.twitter_spaces_get,
    "twitter_find_spaces_by_creator_ids": Executor.twitter_find_spaces_by_creator_ids,
    "twitter_spaces_id_buyers_get": Executor.twitter_spaces_id_buyers_get,
    "twitter_spaces_search_get": Executor.twitter_spaces_search_get,
    "twitter_compliance_jobs_post": Executor.twitter_compliance_jobs_post,
    "twitter_compliance_jobs_get": Executor.twitter_compliance_jobs_get,
    "twitter_compliance_jobs_id_get": Executor.twitter_compliance_jobs_id_get,
    "twitter_users_id_likes_post": Executor.twitter_users_id_likes_post,
    "twitter_users_id_liked_tweets_get": Executor.twitter_users_id_liked_tweets_get,
    "twitter_tweets_id_liking_users_get": Executor.twitter_tweets_id_liking_users_get,
    "twitter_users_id_likes_tweet_id_delete": Executor.twitter_users_id_likes_tweet_id_delete,
    "twitter_users_id_retweets_post": Executor.twitter_users_id_retweets_post,
    "twitter_tweets_id_retweeted_by_get": Executor.twitter_tweets_id_retweeted_by_get,
    "twitter_users_id_retweets_source_tweet_id_delete": Executor.twitter_users_id_retweets_source_tweet_id_delete,
    "twitter_users_id_bookmarks_post": Executor.twitter_users_id_bookmarks_post,
    "twitter_users_id_bookmarks_get": Executor.twitter_users_id_bookmarks_get,
    "twitter_users_id_bookmarks_tweet_id_delete": Executor.twitter_users_id_bookmarks_tweet_id_delete,
    "twitter_users_id_timelines_reverse_chronological_get": Executor.twitter_users_id_timelines_reverse_chronological_get,
    "twitter_users_id_tweets_get": Executor.twitter_users_id_tweets_get,
    "twitter_users_id_mentions_get": Executor.twitter_users_id_mentions_get,
    "twitter_dm_conversations_with_participant_id_dm_events_get": Executor.twitter_dm_conversations_with_participant_id_dm_events_get,
    "twitter_get_dm_conversations_id_dm_events": Executor.twitter_get_dm_conversations_id_dm_events,
    "twitter_dm_events_get": Executor.twitter_dm_events_get,
    "twitter_dm_conversations_with_participant_id_messages_post": Executor.twitter_dm_conversations_with_participant_id_messages_post,
    "twitter_dm_conversation_id_create": Executor.twitter_dm_conversation_id_create,
    "twitter_dm_conversations_dm_conversation_id_messages_post": Executor.twitter_dm_conversations_dm_conversation_id_messages_post
}
