# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    OpenAPI spec version: 2.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CompanyScroll(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'data': 'list[Company]',
        'pages': 'CursorPages',
        'total_count': 'int',
        'scroll_param': 'str'
    }

    attribute_map = {
        'type': 'type',
        'data': 'data',
        'pages': 'pages',
        'total_count': 'total_count',
        'scroll_param': 'scroll_param'
    }

    def __init__(self, type=None, data=None, pages=None, total_count=None, scroll_param=None):  # noqa: E501
        """CompanyScroll - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._data = None
        self._pages = None
        self._total_count = None
        self._scroll_param = None
        self.discriminator = None
        self.type = type
        self.data = data
        if pages is not None:
            self.pages = pages
        self.total_count = total_count
        if scroll_param is not None:
            self.scroll_param = scroll_param

    @property
    def type(self):
        """Gets the type of this CompanyScroll.  # noqa: E501

        The type of object - `list`  # noqa: E501

        :return: The type of this CompanyScroll.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CompanyScroll.

        The type of object - `list`  # noqa: E501

        :param type: The type of this CompanyScroll.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["list"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def data(self):
        """Gets the data of this CompanyScroll.  # noqa: E501


        :return: The data of this CompanyScroll.  # noqa: E501
        :rtype: list[Company]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CompanyScroll.


        :param data: The data of this CompanyScroll.  # noqa: E501
        :type: list[Company]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def pages(self):
        """Gets the pages of this CompanyScroll.  # noqa: E501


        :return: The pages of this CompanyScroll.  # noqa: E501
        :rtype: CursorPages
        """
        return self._pages

    @pages.setter
    def pages(self, pages):
        """Sets the pages of this CompanyScroll.


        :param pages: The pages of this CompanyScroll.  # noqa: E501
        :type: CursorPages
        """

        self._pages = pages

    @property
    def total_count(self):
        """Gets the total_count of this CompanyScroll.  # noqa: E501

        The total number of companies  # noqa: E501

        :return: The total_count of this CompanyScroll.  # noqa: E501
        :rtype: int
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count):
        """Sets the total_count of this CompanyScroll.

        The total number of companies  # noqa: E501

        :param total_count: The total_count of this CompanyScroll.  # noqa: E501
        :type: int
        """
        if total_count is None:
            raise ValueError("Invalid value for `total_count`, must not be `None`")  # noqa: E501

        self._total_count = total_count

    @property
    def scroll_param(self):
        """Gets the scroll_param of this CompanyScroll.  # noqa: E501

        The scroll parameter to use in the next request to fetch the next page of results.  # noqa: E501

        :return: The scroll_param of this CompanyScroll.  # noqa: E501
        :rtype: str
        """
        return self._scroll_param

    @scroll_param.setter
    def scroll_param(self, scroll_param):
        """Sets the scroll_param of this CompanyScroll.

        The scroll parameter to use in the next request to fetch the next page of results.  # noqa: E501

        :param scroll_param: The scroll_param of this CompanyScroll.  # noqa: E501
        :type: str
        """

        self._scroll_param = scroll_param

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompanyScroll, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompanyScroll):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
