# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    OpenAPI spec version: 2.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConvertVisitorRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'user': 'ConvertVisitorRequestUser',
        'visitor': 'ConvertVisitorRequestVisitor'
    }

    attribute_map = {
        'type': 'type',
        'user': 'user',
        'visitor': 'visitor'
    }

    def __init__(self, type=None, user=None, visitor=None):  # noqa: E501
        """ConvertVisitorRequest - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._user = None
        self._visitor = None
        self.discriminator = None
        self.type = type
        self.user = user
        self.visitor = visitor

    @property
    def type(self):
        """Gets the type of this ConvertVisitorRequest.  # noqa: E501

        Represents the role of the Contact model. Accepts `lead` or `user`.  # noqa: E501

        :return: The type of this ConvertVisitorRequest.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ConvertVisitorRequest.

        Represents the role of the Contact model. Accepts `lead` or `user`.  # noqa: E501

        :param type: The type of this ConvertVisitorRequest.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def user(self):
        """Gets the user of this ConvertVisitorRequest.  # noqa: E501


        :return: The user of this ConvertVisitorRequest.  # noqa: E501
        :rtype: ConvertVisitorRequestUser
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this ConvertVisitorRequest.


        :param user: The user of this ConvertVisitorRequest.  # noqa: E501
        :type: ConvertVisitorRequestUser
        """
        if user is None:
            raise ValueError("Invalid value for `user`, must not be `None`")  # noqa: E501

        self._user = user

    @property
    def visitor(self):
        """Gets the visitor of this ConvertVisitorRequest.  # noqa: E501


        :return: The visitor of this ConvertVisitorRequest.  # noqa: E501
        :rtype: ConvertVisitorRequestVisitor
        """
        return self._visitor

    @visitor.setter
    def visitor(self, visitor):
        """Sets the visitor of this ConvertVisitorRequest.


        :param visitor: The visitor of this ConvertVisitorRequest.  # noqa: E501
        :type: ConvertVisitorRequestVisitor
        """
        if visitor is None:
            raise ValueError("Invalid value for `visitor`, must not be `None`")  # noqa: E501

        self._visitor = visitor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConvertVisitorRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConvertVisitorRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
