# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    OpenAPI spec version: 2.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DetachContactFromConversationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'admin_id': 'str'
    }

    attribute_map = {
        'admin_id': 'admin_id'
    }

    def __init__(self, admin_id=None):  # noqa: E501
        """DetachContactFromConversationRequest - a model defined in Swagger"""  # noqa: E501
        self._admin_id = None
        self.discriminator = None
        self.admin_id = admin_id

    @property
    def admin_id(self):
        """Gets the admin_id of this DetachContactFromConversationRequest.  # noqa: E501

        The `id` of the admin who is performing the action.  # noqa: E501

        :return: The admin_id of this DetachContactFromConversationRequest.  # noqa: E501
        :rtype: str
        """
        return self._admin_id

    @admin_id.setter
    def admin_id(self, admin_id):
        """Sets the admin_id of this DetachContactFromConversationRequest.

        The `id` of the admin who is performing the action.  # noqa: E501

        :param admin_id: The admin_id of this DetachContactFromConversationRequest.  # noqa: E501
        :type: str
        """
        if admin_id is None:
            raise ValueError("Invalid value for `admin_id`, must not be `None`")  # noqa: E501

        self._admin_id = admin_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DetachContactFromConversationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DetachContactFromConversationRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
