# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    OpenAPI spec version: 2.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SegmentList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'segments': 'list[Segment]',
        'pages': 'object'
    }

    attribute_map = {
        'type': 'type',
        'segments': 'segments',
        'pages': 'pages'
    }

    def __init__(self, type=None, segments=None, pages=None):  # noqa: E501
        """SegmentList - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._segments = None
        self._pages = None
        self.discriminator = None
        self.type = type
        self.segments = segments
        if pages is not None:
            self.pages = pages

    @property
    def type(self):
        """Gets the type of this SegmentList.  # noqa: E501

        The type of the object  # noqa: E501

        :return: The type of this SegmentList.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SegmentList.

        The type of the object  # noqa: E501

        :param type: The type of this SegmentList.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["segment.list"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def segments(self):
        """Gets the segments of this SegmentList.  # noqa: E501

        A list of Segment objects  # noqa: E501

        :return: The segments of this SegmentList.  # noqa: E501
        :rtype: list[Segment]
        """
        return self._segments

    @segments.setter
    def segments(self, segments):
        """Sets the segments of this SegmentList.

        A list of Segment objects  # noqa: E501

        :param segments: The segments of this SegmentList.  # noqa: E501
        :type: list[Segment]
        """
        if segments is None:
            raise ValueError("Invalid value for `segments`, must not be `None`")  # noqa: E501

        self._segments = segments

    @property
    def pages(self):
        """Gets the pages of this SegmentList.  # noqa: E501

        A pagination object, which may be empty, indicating no further pages to fetch.  # noqa: E501

        :return: The pages of this SegmentList.  # noqa: E501
        :rtype: object
        """
        return self._pages

    @pages.setter
    def pages(self, pages):
        """Sets the pages of this SegmentList.

        A pagination object, which may be empty, indicating no further pages to fetch.  # noqa: E501

        :param pages: The pages of this SegmentList.  # noqa: E501
        :type: object
        """

        self._pages = pages

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SegmentList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SegmentList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
