# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    OpenAPI spec version: 2.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StartingAfterPaging(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'per_page': 'int',
        'starting_after': 'str'
    }

    attribute_map = {
        'per_page': 'per_page',
        'starting_after': 'starting_after'
    }

    def __init__(self, per_page=None, starting_after=None):  # noqa: E501
        """StartingAfterPaging - a model defined in Swagger"""  # noqa: E501
        self._per_page = None
        self._starting_after = None
        self.discriminator = None
        self.per_page = per_page
        if starting_after is not None:
            self.starting_after = starting_after

    @property
    def per_page(self):
        """Gets the per_page of this StartingAfterPaging.  # noqa: E501

        The number of results to fetch per page.  # noqa: E501

        :return: The per_page of this StartingAfterPaging.  # noqa: E501
        :rtype: int
        """
        return self._per_page

    @per_page.setter
    def per_page(self, per_page):
        """Sets the per_page of this StartingAfterPaging.

        The number of results to fetch per page.  # noqa: E501

        :param per_page: The per_page of this StartingAfterPaging.  # noqa: E501
        :type: int
        """
        if per_page is None:
            raise ValueError("Invalid value for `per_page`, must not be `None`")  # noqa: E501

        self._per_page = per_page

    @property
    def starting_after(self):
        """Gets the starting_after of this StartingAfterPaging.  # noqa: E501

        The cursor to use in the next request to get the next page of results.  # noqa: E501

        :return: The starting_after of this StartingAfterPaging.  # noqa: E501
        :rtype: str
        """
        return self._starting_after

    @starting_after.setter
    def starting_after(self, starting_after):
        """Sets the starting_after of this StartingAfterPaging.

        The cursor to use in the next request to get the next page of results.  # noqa: E501

        :param starting_after: The starting_after of this StartingAfterPaging.  # noqa: E501
        :type: str
        """

        self._starting_after = starting_after

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StartingAfterPaging, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StartingAfterPaging):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
