# coding: utf-8

"""
    Intercom API

    The intercom API reference.  # noqa: E501

    OpenAPI spec version: 2.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VisitorDeletedObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'type': 'str',
        'user_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'user_id': 'user_id'
    }

    def __init__(self, id=None, type=None, user_id=None):  # noqa: E501
        """VisitorDeletedObject - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._type = None
        self._user_id = None
        self.discriminator = None
        self.id = id
        self.type = type
        self.user_id = user_id

    @property
    def id(self):
        """Gets the id of this VisitorDeletedObject.  # noqa: E501

        The unique identifier for the visitor which is given by Intercom.  # noqa: E501

        :return: The id of this VisitorDeletedObject.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this VisitorDeletedObject.

        The unique identifier for the visitor which is given by Intercom.  # noqa: E501

        :param id: The id of this VisitorDeletedObject.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def type(self):
        """Gets the type of this VisitorDeletedObject.  # noqa: E501

        The type of object which was deleted  # noqa: E501

        :return: The type of this VisitorDeletedObject.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this VisitorDeletedObject.

        The type of object which was deleted  # noqa: E501

        :param type: The type of this VisitorDeletedObject.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["visitor"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def user_id(self):
        """Gets the user_id of this VisitorDeletedObject.  # noqa: E501

        Automatically generated identifier for the Visitor.  # noqa: E501

        :return: The user_id of this VisitorDeletedObject.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this VisitorDeletedObject.

        Automatically generated identifier for the Visitor.  # noqa: E501

        :param user_id: The user_id of this VisitorDeletedObject.  # noqa: E501
        :type: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VisitorDeletedObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VisitorDeletedObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
